NotificationCenter.Web/Controllers/AccountsController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using NotificationCenter.Core.Services;
using NotificationCenter.Web.Models.Accounts;

namespace NotificationCenter.Web.Controllers
{
    /// <summary>
    /// The accounts controller.
    /// </summary>
    /// <seealso cref="Controller" />
    public class AccountsController : Controller
    {
        #region Fields

        private readonly IUsersService _usersService;
        private readonly IAuthenticationManager _authenticationManager;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsController"/> class.
        /// </summary>
        public AccountsController(
            IUsersService usersService,
            IAuthenticationManager authenticationManager)
        {
            _usersService = usersService;
            _authenticationManager = authenticationManager;
        }

        #endregion

        #region Actions

        /// <summary>
        /// The login GET action.
        /// </summary>
        [HttpGet]
        public ActionResult Login()
        {
            var viewModel = new LoginViewModel();

            return View(viewModel);
        }

        /// <summary>
        /// The login POST action.
        /// </summary>
        /// <param name="viewModel">The view model.</param>
        [HttpPost]
        [ActionName("Login")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoginAsync(LoginViewModel viewModel, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            // TODO : Make password with hash and salt.
            int? userId = await _usersService.GetUserIdByCredentialsAsync(viewModel.UserName, viewModel.Password);

            if (!userId.HasValue)
            {
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Invalid username or password.");

                return View(viewModel);
            }

            var authProperties = new AuthenticationProperties
            {
                IsPersistent = viewModel.RememberMe
            };

            var identity = new ClaimsIdentity(DefaultAuthenticationTypes.ApplicationCookie);

            identity.AddClaim(new Claim(ClaimTypes.Sid, userId.Value.ToString()));
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, viewModel.UserName));
            identity.AddClaim(new Claim(ClaimTypes.Name, viewModel.UserName));

            _authenticationManager.SignIn(authProperties, identity);

            if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            _authenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return RedirectToAction("Login");
        }

        #endregion
    }
}

NotificationCenter.Web/Controllers/CertificatesController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using NotificationCenter.Core.Services;
using NotificationCenter.Models.Domains.Certificates;
using NotificationCenter.Web.Models.Certificates;

namespace NotificationCenter.Web.Controllers
{
    /// <summary>
    /// The certificates controller.
    /// </summary>
    /// <seealso cref="Controller" />
    [Authorize]
    public class CertificatesController : Controller
    {
        #region Fields

        private readonly ICertificatesService _certificatesService;
        private readonly IClientsService _clientsService;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesController"/> class.
        /// </summary>
        /// <param name="certificatesService">The certificates service.</param>
        public CertificatesController(
            ICertificatesService certificatesService,
            IClientsService clientsService)
        {
            _certificatesService = certificatesService;
            _clientsService = clientsService;
        }

        #endregion

        /// <summary>
        /// Creates certificate. Get Action.
        /// </summary>
        [HttpGet]
        [ActionName("Create")]
        public async Task<ActionResult> CreateAsync()
        {
            var viewModel = new CertificateViewModel();

            viewModel.Clients = await _clientsService.GetAllAsync();

            return View(viewModel);
        }

        /// <summary>
        /// Creates certificate. POST Action.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Create")]
        public async Task<ActionResult> CreateAsync(CertificateViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Clients = await _clientsService.GetAllAsync();

                return View(viewModel);
            }

            // For testing (demonstrating) purposes.
            DateTime validTo = DateTime.Now.AddMinutes(2);

            var domain = new Certificate(0, viewModel.Number, viewModel.ValidFrom.Value, validTo, viewModel.ClientId.Value);

            int id = await _certificatesService.CreateAsync(domain);

            return RedirectToAction("Index", "Home");
        }
    }
}

NotificationCenter.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Notification Center</title>

    <link href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Notification Center", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Orders", "Index", "Home")</li>
                    <li>@Html.ActionLink("Create certificate", "Create", "Certificates")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "Accounts")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top: 100px">
        @RenderBody()
    </div>

    <script type="text/javascript" src="~/bower_components/jQuery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/bower_components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/bower_components/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Content/js/common/jquery.val.bootstrap.js"></script>
    <script type="text/javascript" src="~/bower_components/signalr/jquery.signalR.js"></script>
    <script type="text/javascript" src="~/signalr/hubs"></script>
    <script type="text/javascript" src="~/Content/js/notifications/notifications.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

NotificationCenter.Web/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Notification Center</title>

    <link href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <script type="text/javascript" src="~/bower_components/jQuery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/bower_components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/bower_components/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Content/js/common/jquery.val.bootstrap.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>